name: Git LFS

on:
  push:
    paths:
      - .github/workflows/git-lfs.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - run: git config -l
      - run: git lfs env
      - uses: actions/checkout@v3
        with:
          lfs: true
      - run: cat large.txt
      - run: echo 'large file' >> large.txt
      - run: git lfs track
      - run: git lfs track '*.txt'
      - run: git lfs track
      - run: git lfs ls-files
      - uses: snow-actions/git-config-user@v1.0.0
      - run: git add .
      - run: git commit -m 'Large file'
      - run: git push
